// Code generated by entc, DO NOT EDIT.

package index

import (
	"time"
)

const (
	// Label holds the string label denoting the index type in the database.
	Label = "index"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldContentID holds the string denoting the content_id field in the database.
	FieldContentID = "content_id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldDesc holds the string denoting the desc field in the database.
	FieldDesc = "desc"
	// FieldAttr holds the string denoting the attr field in the database.
	FieldAttr = "attr"
	// FieldView holds the string denoting the view field in the database.
	FieldView = "view"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// Table holds the table name of the index in the database.
	Table = "blog_index"
)

// Columns holds all SQL columns for index fields.
var Columns = []string{
	FieldID,
	FieldContentID,
	FieldTitle,
	FieldDesc,
	FieldAttr,
	FieldView,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldState,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// DefaultAttr holds the default value on creation for the "attr" field.
	DefaultAttr int32
	// DefaultView holds the default value on creation for the "view" field.
	DefaultView int32
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// DefaultState holds the default value on creation for the "state" field.
	DefaultState int8
)
