// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/samb233/easyblog/internal/data/ent/content"
	"github.com/samb233/easyblog/internal/data/ent/index"
	"github.com/samb233/easyblog/internal/data/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	contentFields := schema.Content{}.Fields()
	_ = contentFields
	// contentDescCreatedAt is the schema descriptor for created_at field.
	contentDescCreatedAt := contentFields[2].Descriptor()
	// content.DefaultCreatedAt holds the default value on creation for the created_at field.
	content.DefaultCreatedAt = contentDescCreatedAt.Default.(func() time.Time)
	// contentDescUpdatedAt is the schema descriptor for updated_at field.
	contentDescUpdatedAt := contentFields[3].Descriptor()
	// content.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	content.DefaultUpdatedAt = contentDescUpdatedAt.Default.(func() time.Time)
	indexFields := schema.Index{}.Fields()
	_ = indexFields
	// indexDescTitle is the schema descriptor for title field.
	indexDescTitle := indexFields[2].Descriptor()
	// index.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	index.TitleValidator = indexDescTitle.Validators[0].(func(string) error)
	// indexDescAttr is the schema descriptor for attr field.
	indexDescAttr := indexFields[4].Descriptor()
	// index.DefaultAttr holds the default value on creation for the attr field.
	index.DefaultAttr = indexDescAttr.Default.(int32)
	// indexDescView is the schema descriptor for view field.
	indexDescView := indexFields[5].Descriptor()
	// index.DefaultView holds the default value on creation for the view field.
	index.DefaultView = indexDescView.Default.(int32)
	// indexDescCreatedAt is the schema descriptor for created_at field.
	indexDescCreatedAt := indexFields[6].Descriptor()
	// index.DefaultCreatedAt holds the default value on creation for the created_at field.
	index.DefaultCreatedAt = indexDescCreatedAt.Default.(func() time.Time)
	// indexDescUpdatedAt is the schema descriptor for updated_at field.
	indexDescUpdatedAt := indexFields[7].Descriptor()
	// index.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	index.DefaultUpdatedAt = indexDescUpdatedAt.Default.(func() time.Time)
	// indexDescState is the schema descriptor for state field.
	indexDescState := indexFields[8].Descriptor()
	// index.DefaultState holds the default value on creation for the state field.
	index.DefaultState = indexDescState.Default.(int8)
}
